### ISSUE TITLE
index 页面左边栏尺寸问题

### ISSUE THREAD

**Issue by clouduan** [mythsman/blog#1]
如图，左边栏下面的一些 icons 看不到，我网页缩放后才能看到，博主可以调节一下。

![default](https://user-images.githubusercontent.com/20282795/38767784-79d43bc8-401a-11e8-84e2-b03e9df53d19.PNG)

**Comment by mythsman** [comment]
这个还真不好调。。。不同浏览器的默认缩放比好像是不一样的。。。主要还是因为我这边菜单太长了。。。。。。。
